### ISSUE TITLE
Implement authentication server to generate SAS token

### ISSUE THREAD

**Issue by madushadhanushka** [wso2/apim-analytics-publisher#10]
**Description**
The authentication server is responsible for authenticating agents and issue a new SAS token that can be used to publish events. Token generation information is kept inside a database for each deployment. Auth server authenticates the user with incoming JWT with a token endpoint. consumer key is taken from the JWT and extracts the relevant publisher name and the tokens need to generate the SAS token. Generated SAS token reply back to the client.

**Comment by madushadhanushka** [comment]
Agent implementation task https://github.com/wso2/apim-analytics-publisher/issues/9

**Comment by madushadhanushka** [comment]
Fixed with https://github.com/wso2-enterprise/choreo-apim-analytics-auth-api/pull/9

**Comment by tishan89** [comment]
@madushadhanushka Can you please close this issue if the task is done
