### ISSUE TITLE
When the Token to Analytics is expired API requests fail with 401

### ISSUE THREAD

**Issue by jaadds** [wso2/apim-analytics-publisher#22]
**Description:**
Used an Invalid Token (token used to publish Analytics Events) while starting the Gateway. Invoked an API, which was working earlier. Got the following error while invoking the API.

com.azure.core.amqp.exception.AmqpException: status-code: 401, status-description: ExpiredToken: The token is expired. Expiration time: '2021-02-01 06:19:27Z', errorContext[NAMESPACE: analytics-dev-eventhub.servicebus.windows.net, PATH: $cbs, REFERENCE_ID: cbs:receiver, LINK_CREDIT: 0]

Received the following error as the response:

{"Fault":{"faultcode":"soapenv:Server","faultstring":"status-code: 401, status-description: ExpiredToken: The token is expired. Expiration time: '2021-02-01 06:19:27Z', errorContext[NAMESPACE: analytics-dev-eventhub.servicebus.windows.net, PATH: $cbs, REFERENCE_ID: cbs:receiver, LINK_CREDIT: 0]","detail":null}

**Comment by tishan89** [comment]
handled with https://github.com/wso2/apim-analytics-publisher/pull/38
